/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedRentalReturnRouteImport } from './routes/_authenticated/rental-return'
import { Route as AuthenticatedQuickExchangemChar225solataRouteImport } from './routes/_authenticated/quick-exchange másolata'
import { Route as AuthenticatedQuickExchangeRouteImport } from './routes/_authenticated/quick-exchange'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCylindersRouteImport } from './routes/_authenticated/cylinders'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCylindersIdRouteImport } from './routes/_authenticated/cylinders.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalReturnRoute =
  AuthenticatedRentalReturnRouteImport.update({
    id: '/rental-return',
    path: '/rental-return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuickExchangemChar225solataRoute =
  AuthenticatedQuickExchangemChar225solataRouteImport.update({
    id: '/quick-exchange másolata',
    path: '/quick-exchange másolata',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuickExchangeRoute =
  AuthenticatedQuickExchangeRouteImport.update({
    id: '/quick-exchange',
    path: '/quick-exchange',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCylindersRoute = AuthenticatedCylindersRouteImport.update({
  id: '/cylinders',
  path: '/cylinders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCylindersIdRoute =
  AuthenticatedCylindersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCylindersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cylinders': typeof AuthenticatedCylindersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/more': typeof AuthenticatedMoreRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/quick-exchange': typeof AuthenticatedQuickExchangeRoute
  '/quick-exchange másolata': typeof AuthenticatedQuickExchangemChar225solataRoute
  '/rental-return': typeof AuthenticatedRentalReturnRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/cylinders/$id': typeof AuthenticatedCylindersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cylinders': typeof AuthenticatedCylindersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/more': typeof AuthenticatedMoreRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/quick-exchange': typeof AuthenticatedQuickExchangeRoute
  '/quick-exchange másolata': typeof AuthenticatedQuickExchangemChar225solataRoute
  '/rental-return': typeof AuthenticatedRentalReturnRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/cylinders/$id': typeof AuthenticatedCylindersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/cylinders': typeof AuthenticatedCylindersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/quick-exchange': typeof AuthenticatedQuickExchangeRoute
  '/_authenticated/quick-exchange másolata': typeof AuthenticatedQuickExchangemChar225solataRoute
  '/_authenticated/rental-return': typeof AuthenticatedRentalReturnRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/cylinders/$id': typeof AuthenticatedCylindersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/cylinders'
    | '/dashboard'
    | '/more'
    | '/partners'
    | '/quick-exchange'
    | '/quick-exchange másolata'
    | '/rental-return'
    | '/suppliers'
    | '/cylinders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/cylinders'
    | '/dashboard'
    | '/more'
    | '/partners'
    | '/quick-exchange'
    | '/quick-exchange másolata'
    | '/rental-return'
    | '/suppliers'
    | '/cylinders/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/cylinders'
    | '/_authenticated/dashboard'
    | '/_authenticated/more'
    | '/_authenticated/partners'
    | '/_authenticated/quick-exchange'
    | '/_authenticated/quick-exchange másolata'
    | '/_authenticated/rental-return'
    | '/_authenticated/suppliers'
    | '/_authenticated/cylinders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rental-return': {
      id: '/_authenticated/rental-return'
      path: '/rental-return'
      fullPath: '/rental-return'
      preLoaderRoute: typeof AuthenticatedRentalReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-exchange másolata': {
      id: '/_authenticated/quick-exchange másolata'
      path: '/quick-exchange másolata'
      fullPath: '/quick-exchange másolata'
      preLoaderRoute: typeof AuthenticatedQuickExchangemChar225solataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-exchange': {
      id: '/_authenticated/quick-exchange'
      path: '/quick-exchange'
      fullPath: '/quick-exchange'
      preLoaderRoute: typeof AuthenticatedQuickExchangeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cylinders': {
      id: '/_authenticated/cylinders'
      path: '/cylinders'
      fullPath: '/cylinders'
      preLoaderRoute: typeof AuthenticatedCylindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cylinders/$id': {
      id: '/_authenticated/cylinders/$id'
      path: '/$id'
      fullPath: '/cylinders/$id'
      preLoaderRoute: typeof AuthenticatedCylindersIdRouteImport
      parentRoute: typeof AuthenticatedCylindersRoute
    }
  }
}

interface AuthenticatedCylindersRouteChildren {
  AuthenticatedCylindersIdRoute: typeof AuthenticatedCylindersIdRoute
}

const AuthenticatedCylindersRouteChildren: AuthenticatedCylindersRouteChildren =
  {
    AuthenticatedCylindersIdRoute: AuthenticatedCylindersIdRoute,
  }

const AuthenticatedCylindersRouteWithChildren =
  AuthenticatedCylindersRoute._addFileChildren(
    AuthenticatedCylindersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCylindersRoute: typeof AuthenticatedCylindersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedQuickExchangeRoute: typeof AuthenticatedQuickExchangeRoute
  AuthenticatedQuickExchangemChar225solataRoute: typeof AuthenticatedQuickExchangemChar225solataRoute
  AuthenticatedRentalReturnRoute: typeof AuthenticatedRentalReturnRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCylindersRoute: AuthenticatedCylindersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedQuickExchangeRoute: AuthenticatedQuickExchangeRoute,
  AuthenticatedQuickExchangemChar225solataRoute:
    AuthenticatedQuickExchangemChar225solataRoute,
  AuthenticatedRentalReturnRoute: AuthenticatedRentalReturnRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
