/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedRentalsRouteImport } from './routes/_authenticated/rentals'
import { Route as AuthenticatedRentalReturnRouteImport } from './routes/_authenticated/rental-return'
import { Route as AuthenticatedQuickExchangeRouteImport } from './routes/_authenticated/quick-exchange'
import { Route as AuthenticatedPriceListRouteImport } from './routes/_authenticated/price-list'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedGasOrderRouteImport } from './routes/_authenticated/gas-order'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCylindersRouteImport } from './routes/_authenticated/cylinders'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedRentalsIndexRouteImport } from './routes/_authenticated/rentals.index'
import { Route as AuthenticatedPartnersIndexRouteImport } from './routes/_authenticated/partners.index'
import { Route as AuthenticatedRentalsIdRouteImport } from './routes/_authenticated/rentals.$id'
import { Route as AuthenticatedPartnersIdRouteImport } from './routes/_authenticated/partners.$id'
import { Route as AuthenticatedCylindersIdRouteImport } from './routes/_authenticated/cylinders.$id'
import { Route as AuthenticatedPartnersIdRentalsRouteImport } from './routes/_authenticated/partners.$id.rentals'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalsRoute = AuthenticatedRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalReturnRoute =
  AuthenticatedRentalReturnRouteImport.update({
    id: '/rental-return',
    path: '/rental-return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuickExchangeRoute =
  AuthenticatedQuickExchangeRouteImport.update({
    id: '/quick-exchange',
    path: '/quick-exchange',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriceListRoute = AuthenticatedPriceListRouteImport.update({
  id: '/price-list',
  path: '/price-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGasOrderRoute = AuthenticatedGasOrderRouteImport.update({
  id: '/gas-order',
  path: '/gas-order',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCylindersRoute = AuthenticatedCylindersRouteImport.update({
  id: '/cylinders',
  path: '/cylinders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalsIndexRoute =
  AuthenticatedRentalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRentalsRoute,
  } as any)
const AuthenticatedPartnersIndexRoute =
  AuthenticatedPartnersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnersRoute,
  } as any)
const AuthenticatedRentalsIdRoute = AuthenticatedRentalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRentalsRoute,
} as any)
const AuthenticatedPartnersIdRoute = AuthenticatedPartnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPartnersRoute,
} as any)
const AuthenticatedCylindersIdRoute =
  AuthenticatedCylindersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCylindersRoute,
  } as any)
const AuthenticatedPartnersIdRentalsRoute =
  AuthenticatedPartnersIdRentalsRouteImport.update({
    id: '/rentals',
    path: '/rentals',
    getParentRoute: () => AuthenticatedPartnersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cylinders': typeof AuthenticatedCylindersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gas-order': typeof AuthenticatedGasOrderRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/more': typeof AuthenticatedMoreRoute
  '/partners': typeof AuthenticatedPartnersRouteWithChildren
  '/price-list': typeof AuthenticatedPriceListRoute
  '/quick-exchange': typeof AuthenticatedQuickExchangeRoute
  '/rental-return': typeof AuthenticatedRentalReturnRoute
  '/rentals': typeof AuthenticatedRentalsRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/cylinders/$id': typeof AuthenticatedCylindersIdRoute
  '/partners/$id': typeof AuthenticatedPartnersIdRouteWithChildren
  '/rentals/$id': typeof AuthenticatedRentalsIdRoute
  '/partners/': typeof AuthenticatedPartnersIndexRoute
  '/rentals/': typeof AuthenticatedRentalsIndexRoute
  '/partners/$id/rentals': typeof AuthenticatedPartnersIdRentalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cylinders': typeof AuthenticatedCylindersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gas-order': typeof AuthenticatedGasOrderRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/more': typeof AuthenticatedMoreRoute
  '/price-list': typeof AuthenticatedPriceListRoute
  '/quick-exchange': typeof AuthenticatedQuickExchangeRoute
  '/rental-return': typeof AuthenticatedRentalReturnRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/cylinders/$id': typeof AuthenticatedCylindersIdRoute
  '/partners/$id': typeof AuthenticatedPartnersIdRouteWithChildren
  '/rentals/$id': typeof AuthenticatedRentalsIdRoute
  '/partners': typeof AuthenticatedPartnersIndexRoute
  '/rentals': typeof AuthenticatedRentalsIndexRoute
  '/partners/$id/rentals': typeof AuthenticatedPartnersIdRentalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/cylinders': typeof AuthenticatedCylindersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gas-order': typeof AuthenticatedGasOrderRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRouteWithChildren
  '/_authenticated/price-list': typeof AuthenticatedPriceListRoute
  '/_authenticated/quick-exchange': typeof AuthenticatedQuickExchangeRoute
  '/_authenticated/rental-return': typeof AuthenticatedRentalReturnRoute
  '/_authenticated/rentals': typeof AuthenticatedRentalsRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/cylinders/$id': typeof AuthenticatedCylindersIdRoute
  '/_authenticated/partners/$id': typeof AuthenticatedPartnersIdRouteWithChildren
  '/_authenticated/rentals/$id': typeof AuthenticatedRentalsIdRoute
  '/_authenticated/partners/': typeof AuthenticatedPartnersIndexRoute
  '/_authenticated/rentals/': typeof AuthenticatedRentalsIndexRoute
  '/_authenticated/partners/$id/rentals': typeof AuthenticatedPartnersIdRentalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/cylinders'
    | '/dashboard'
    | '/gas-order'
    | '/inventory'
    | '/more'
    | '/partners'
    | '/price-list'
    | '/quick-exchange'
    | '/rental-return'
    | '/rentals'
    | '/suppliers'
    | '/cylinders/$id'
    | '/partners/$id'
    | '/rentals/$id'
    | '/partners/'
    | '/rentals/'
    | '/partners/$id/rentals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/cylinders'
    | '/dashboard'
    | '/gas-order'
    | '/inventory'
    | '/more'
    | '/price-list'
    | '/quick-exchange'
    | '/rental-return'
    | '/suppliers'
    | '/cylinders/$id'
    | '/partners/$id'
    | '/rentals/$id'
    | '/partners'
    | '/rentals'
    | '/partners/$id/rentals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/cylinders'
    | '/_authenticated/dashboard'
    | '/_authenticated/gas-order'
    | '/_authenticated/inventory'
    | '/_authenticated/more'
    | '/_authenticated/partners'
    | '/_authenticated/price-list'
    | '/_authenticated/quick-exchange'
    | '/_authenticated/rental-return'
    | '/_authenticated/rentals'
    | '/_authenticated/suppliers'
    | '/_authenticated/cylinders/$id'
    | '/_authenticated/partners/$id'
    | '/_authenticated/rentals/$id'
    | '/_authenticated/partners/'
    | '/_authenticated/rentals/'
    | '/_authenticated/partners/$id/rentals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rentals': {
      id: '/_authenticated/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof AuthenticatedRentalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rental-return': {
      id: '/_authenticated/rental-return'
      path: '/rental-return'
      fullPath: '/rental-return'
      preLoaderRoute: typeof AuthenticatedRentalReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-exchange': {
      id: '/_authenticated/quick-exchange'
      path: '/quick-exchange'
      fullPath: '/quick-exchange'
      preLoaderRoute: typeof AuthenticatedQuickExchangeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price-list': {
      id: '/_authenticated/price-list'
      path: '/price-list'
      fullPath: '/price-list'
      preLoaderRoute: typeof AuthenticatedPriceListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gas-order': {
      id: '/_authenticated/gas-order'
      path: '/gas-order'
      fullPath: '/gas-order'
      preLoaderRoute: typeof AuthenticatedGasOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cylinders': {
      id: '/_authenticated/cylinders'
      path: '/cylinders'
      fullPath: '/cylinders'
      preLoaderRoute: typeof AuthenticatedCylindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rentals/': {
      id: '/_authenticated/rentals/'
      path: '/'
      fullPath: '/rentals/'
      preLoaderRoute: typeof AuthenticatedRentalsIndexRouteImport
      parentRoute: typeof AuthenticatedRentalsRoute
    }
    '/_authenticated/partners/': {
      id: '/_authenticated/partners/'
      path: '/'
      fullPath: '/partners/'
      preLoaderRoute: typeof AuthenticatedPartnersIndexRouteImport
      parentRoute: typeof AuthenticatedPartnersRoute
    }
    '/_authenticated/rentals/$id': {
      id: '/_authenticated/rentals/$id'
      path: '/$id'
      fullPath: '/rentals/$id'
      preLoaderRoute: typeof AuthenticatedRentalsIdRouteImport
      parentRoute: typeof AuthenticatedRentalsRoute
    }
    '/_authenticated/partners/$id': {
      id: '/_authenticated/partners/$id'
      path: '/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof AuthenticatedPartnersIdRouteImport
      parentRoute: typeof AuthenticatedPartnersRoute
    }
    '/_authenticated/cylinders/$id': {
      id: '/_authenticated/cylinders/$id'
      path: '/$id'
      fullPath: '/cylinders/$id'
      preLoaderRoute: typeof AuthenticatedCylindersIdRouteImport
      parentRoute: typeof AuthenticatedCylindersRoute
    }
    '/_authenticated/partners/$id/rentals': {
      id: '/_authenticated/partners/$id/rentals'
      path: '/rentals'
      fullPath: '/partners/$id/rentals'
      preLoaderRoute: typeof AuthenticatedPartnersIdRentalsRouteImport
      parentRoute: typeof AuthenticatedPartnersIdRoute
    }
  }
}

interface AuthenticatedCylindersRouteChildren {
  AuthenticatedCylindersIdRoute: typeof AuthenticatedCylindersIdRoute
}

const AuthenticatedCylindersRouteChildren: AuthenticatedCylindersRouteChildren =
  {
    AuthenticatedCylindersIdRoute: AuthenticatedCylindersIdRoute,
  }

const AuthenticatedCylindersRouteWithChildren =
  AuthenticatedCylindersRoute._addFileChildren(
    AuthenticatedCylindersRouteChildren,
  )

interface AuthenticatedPartnersIdRouteChildren {
  AuthenticatedPartnersIdRentalsRoute: typeof AuthenticatedPartnersIdRentalsRoute
}

const AuthenticatedPartnersIdRouteChildren: AuthenticatedPartnersIdRouteChildren =
  {
    AuthenticatedPartnersIdRentalsRoute: AuthenticatedPartnersIdRentalsRoute,
  }

const AuthenticatedPartnersIdRouteWithChildren =
  AuthenticatedPartnersIdRoute._addFileChildren(
    AuthenticatedPartnersIdRouteChildren,
  )

interface AuthenticatedPartnersRouteChildren {
  AuthenticatedPartnersIdRoute: typeof AuthenticatedPartnersIdRouteWithChildren
  AuthenticatedPartnersIndexRoute: typeof AuthenticatedPartnersIndexRoute
}

const AuthenticatedPartnersRouteChildren: AuthenticatedPartnersRouteChildren = {
  AuthenticatedPartnersIdRoute: AuthenticatedPartnersIdRouteWithChildren,
  AuthenticatedPartnersIndexRoute: AuthenticatedPartnersIndexRoute,
}

const AuthenticatedPartnersRouteWithChildren =
  AuthenticatedPartnersRoute._addFileChildren(
    AuthenticatedPartnersRouteChildren,
  )

interface AuthenticatedRentalsRouteChildren {
  AuthenticatedRentalsIdRoute: typeof AuthenticatedRentalsIdRoute
  AuthenticatedRentalsIndexRoute: typeof AuthenticatedRentalsIndexRoute
}

const AuthenticatedRentalsRouteChildren: AuthenticatedRentalsRouteChildren = {
  AuthenticatedRentalsIdRoute: AuthenticatedRentalsIdRoute,
  AuthenticatedRentalsIndexRoute: AuthenticatedRentalsIndexRoute,
}

const AuthenticatedRentalsRouteWithChildren =
  AuthenticatedRentalsRoute._addFileChildren(AuthenticatedRentalsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCylindersRoute: typeof AuthenticatedCylindersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGasOrderRoute: typeof AuthenticatedGasOrderRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRouteWithChildren
  AuthenticatedPriceListRoute: typeof AuthenticatedPriceListRoute
  AuthenticatedQuickExchangeRoute: typeof AuthenticatedQuickExchangeRoute
  AuthenticatedRentalReturnRoute: typeof AuthenticatedRentalReturnRoute
  AuthenticatedRentalsRoute: typeof AuthenticatedRentalsRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCylindersRoute: AuthenticatedCylindersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGasOrderRoute: AuthenticatedGasOrderRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRouteWithChildren,
  AuthenticatedPriceListRoute: AuthenticatedPriceListRoute,
  AuthenticatedQuickExchangeRoute: AuthenticatedQuickExchangeRoute,
  AuthenticatedRentalReturnRoute: AuthenticatedRentalReturnRoute,
  AuthenticatedRentalsRoute: AuthenticatedRentalsRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
